apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-job-container
        image: ilonamohilnikova/hello:latest
        command: ["bash"]
      restartPolicy: Never
