apiVersion: v1
kind: Pod
metadata:
  name: test-resources
spec:
  containers:
  - name: test-container
    image: ilonamohilnikova/hello:latest
    ports:
    - containerPort: 8080
      name: test-container
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
  
     