apiVersion: v1
kind: Pod
metadata:
  name: test-livenessprobe
  namespace: demo
spec:
  containers:
  - name: app
    image: ilonamohilnikova/hello:latest
    ports:
    - containerPort: 8080
      name: test-server
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 20
      timeoutSeconds: 1
      failureThreshold: 4
