apiVersion: v1
kind: Pod
metadata:
  name: test-config
  labels:
    app: app-config
    run: dev
spec:
  containers:
  - name: pod1
    image: ilonamohilnikova/hello:latest
    imagePullPolicy: Always
    env:
    - name: CONFIG_PARAM
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: config-param
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: knfg
    configMap:
      name: test
  restartPolicy: Never
