apiVersion: v1
kind: Pod
metadata:
  name: test-volume
spec:
  containers:
  - name: test-volume
    image: ilonamohilnikova/hello:latest
    volumeMounts:
    - name: data-storage
      mountPath: /data/test-volume
  volumes:
  - name: data-storage
    emptyDir: {}
